### PR TITLE
WIP: Cleanup

### PR DESCRIPTION
**Pull request by rainwoodman**
We tried to use gcvspline; got stuck compiling the code. 

This is a clean up of the code repo, making it easier to build:

- no longer need to manually trigger f2py
- derived files are removed from the repo
- added a basic test case. I don't have a good unit test, so I copied the example. No assertions are made, but this is a starting point.

### CODE REVIEW

**Comment by rainwoodman** [comment]
- added new GCVSpline interface.

**Comment by rainwoodman** [comment]
- the example I copied to test_gcvspline.py hangs from time to time. It appears the choice of parameter may be problematic.

**Comment by rainwoodman** [comment]
I added a set of scipy.interploate inspired classes for accessing the spline.

**Comment by charlesll** [comment]
Good, thanks for the changes! I indeed noticed this problem, but was too busy to take care of it! Merging the changes! Thanks again!

**Comment by rainwoodman** [comment]
Thanks. There were a few additional changes that I forgot to commit and push. I filed them under a new PR.

**Pull request merged**
